ALTER TABLE CH04_JOIN_EMPLOYEE DROP CONSTRAINT "INHER_JOIN_EMPLOYEE_PERSON_FK"
;

ALTER TABLE CH04_JOIN_EMPLOYEE DROP CONSTRAINT "INHER_JOIN_EMPLOYEE_FT_EMP_FK"
;

ALTER TABLE CH04_JOIN_FT_EMPLOYEE DROP CONSTRAINT "INHER_JOIN_FT_EMP_PERSON_FK"
;

ALTER TABLE CH04_JOIN_PERSON DROP CONSTRAINT "INHER_JOIN_PERSON_ADDRESS_FK"
;

ALTER TABLE CH04_JOIN_PT_EMPLOYEE DROP CONSTRAINT "INHER_JOIN_PT_EMPLOYEE_FK"
;

DROP TABLE CH04_JOIN_ADDRESS CASCADE CONSTRAINTS;

DROP TABLE CH04_JOIN_EMPLOYEE CASCADE CONSTRAINTS;

DROP TABLE CH04_JOIN_FT_EMPLOYEE CASCADE CONSTRAINTS;

DROP TABLE CH04_JOIN_PERSON CASCADE CONSTRAINTS;

DROP TABLE CH04_JOIN_PT_EMPLOYEE CASCADE CONSTRAINTS;

DROP SEQUENCE CH04_JOIN_PERSON_SEQ;

DROP SEQUENCE CH04_JOIN_ADDRESS_SEQ;

CREATE TABLE CH04_JOIN_ADDRESS
(
ID INTEGER NOT NULL,
VERSION INTEGER,
STREET1 VARCHAR2(100),
STREET2 VARCHAR2(100),
CITY VARCHAR2(50),
STATE VARCHAR2(2),
ZIP_CODE INTEGER
)
;

CREATE TABLE CH04_JOIN_EMPLOYEE
(
ID INTEGER NOT NULL,
EMAIL VARCHAR2(50),
DEPT VARCHAR2(30),
MANAGER INTEGER
)
;

CREATE TABLE CH04_JOIN_FT_EMPLOYEE
(
ID INTEGER NOT NULL,
ANNUAL_SALARY NUMBER(8, 2)
)
;

CREATE TABLE CH04_JOIN_PERSON
(
ID INTEGER NOT NULL,
TYPE VARCHAR2(30),
VERSION INTEGER,
FIRST_NAME VARCHAR2(30),
LAST_NAME VARCHAR2(30),
HOME_ADDRESS INTEGER
)
;

CREATE TABLE CH04_JOIN_PT_EMPLOYEE
(
ID INTEGER NOT NULL,
HOURLY_WAGE NUMBER(8, 2)
)
;

ALTER TABLE CH04_JOIN_ADDRESS
ADD CONSTRAINT INHER_JOIN_ADDRESS_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE CH04_JOIN_EMPLOYEE
ADD CONSTRAINT INHER_JOIN_EMPLOYEE_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE CH04_JOIN_FT_EMPLOYEE
ADD CONSTRAINT INHER_JOIN_FT_EMPLOYEE_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE CH04_JOIN_PERSON
ADD CONSTRAINT INHER_JOIN_PERSON_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE CH04_JOIN_PERSON
ADD CONSTRAINT INHER_JOIN_HOME_ADDRESS_UK UNIQUE
(
HOME_ADDRESS
)
 ENABLE
;

ALTER TABLE CH04_JOIN_PT_EMPLOYEE
ADD CONSTRAINT INHER_JOIN_PT_EMPLOYEE_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE CH04_JOIN_EMPLOYEE
ADD CONSTRAINT INHER_JOIN_EMPLOYEE_PERSON_FK FOREIGN KEY
(
ID
)
REFERENCES CH04_JOIN_PERSON
(
ID
) ENABLE
;

ALTER TABLE CH04_JOIN_EMPLOYEE
ADD CONSTRAINT INHER_JOIN_EMPLOYEE_FT_EMP_FK FOREIGN KEY
(
MANAGER
)
REFERENCES CH04_JOIN_FT_EMPLOYEE
(
ID
) ENABLE
;

ALTER TABLE CH04_JOIN_FT_EMPLOYEE
ADD CONSTRAINT INHER_JOIN_FT_EMP_PERSON_FK FOREIGN KEY
(
ID
)
REFERENCES CH04_JOIN_PERSON
(
ID
) ENABLE
;

ALTER TABLE CH04_JOIN_PERSON
ADD CONSTRAINT INHER_JOIN_PERSON_ADDRESS_FK FOREIGN KEY
(
HOME_ADDRESS
)
REFERENCES CH04_JOIN_ADDRESS
(
ID
) ENABLE
;

ALTER TABLE CH04_JOIN_PT_EMPLOYEE
ADD CONSTRAINT INHER_JOIN_PT_EMPLOYEE_FK FOREIGN KEY
(
ID
)
REFERENCES CH04_JOIN_PERSON
(
ID
) ENABLE
;

CREATE SEQUENCE CH04_JOIN_PERSON_SEQ INCREMENT BY 50 START WITH 100 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE CH04_JOIN_ADDRESS_SEQ INCREMENT BY 50 START WITH 100 MINVALUE 1 CACHE 20 ;

