ALTER TABLE CH04_EMB_PERSON DROP CONSTRAINT "EMBEDDABLE_PERSON_EMPLOYEE_FK"
;

DROP TABLE CH04_EMB_PERSON CASCADE CONSTRAINTS;

DROP SEQUENCE CH04_EMB_PERSON_SEQ;

CREATE TABLE CH04_EMB_PERSON
(
ID NUMBER(*, 0) NOT NULL,
TYPE VARCHAR2(30) NOT NULL,
VERSION NUMBER(*, 0) NOT NULL,
FIRST_NAME VARCHAR2(30),
LAST_NAME VARCHAR2(30),
DEPT VARCHAR2(30),
EMAIL VARCHAR2(50),
MANAGER NUMBER(*, 0),
ANNUAL_SALARY NUMBER(8, 2),
HOURLY_WAGE NUMBER(8, 2),
STREET1 VARCHAR2(100),
STREET2 VARCHAR2(100),
CITY VARCHAR2(50),
STATE VARCHAR2(2),
ZIP_CODE INTEGER
)
;

ALTER TABLE CH04_EMB_PERSON
ADD CONSTRAINT EMBEDDABLE_PERSON_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE CH04_EMB_PERSON
ADD CONSTRAINT EMBEDDABLE_PERSON_EMPLOYEE_FK FOREIGN KEY
(
MANAGER
)
REFERENCES CH04_EMB_PERSON
(
ID
) ENABLE
;

CREATE SEQUENCE CH04_EMB_PERSON_SEQ INCREMENT BY 50 START WITH 100 MINVALUE 1 CACHE 20 ;

