
package com.apress.ejb3.credit;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_03-b18-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "CreditService", targetNamespace = "http://www.apress.com/ejb3/credit", wsdlLocation = "http://localhost:8080/CreditService/CreditCheckEndpointBean?WSDL")
public class CreditService
    extends Service
{

    private final static URL CREDITSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/CreditService/CreditCheckEndpointBean?WSDL");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        CREDITSERVICE_WSDL_LOCATION = url;
    }

    public CreditService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditService() {
        super(CREDITSERVICE_WSDL_LOCATION, new QName("http://www.apress.com/ejb3/credit", "CreditService"));
    }

    /**
     * 
     * @return
     *     returns CreditCheckEndpointBean
     */
    @WebEndpoint(name = "CreditCheckEndpointBeanPort")
    public CreditCheckEndpointBean getCreditCheckEndpointBeanPort() {
        return (CreditCheckEndpointBean)super.getPort(new QName("http://www.apress.com/ejb3/credit", "CreditCheckEndpointBeanPort"), CreditCheckEndpointBean.class);
    }

}
