ALTER TABLE CH04_ST_PERSON DROP CONSTRAINT "INHER_ST_PERSON_ADDRESS_FK"
;

ALTER TABLE CH04_ST_PERSON DROP CONSTRAINT "INHER_ST_PERSON_EMPLOYEE_FK"
;

DROP TABLE CH04_ST_ADDRESS CASCADE CONSTRAINTS;

DROP SEQUENCE CH04_ST_ADDRESS_SEQ;

DROP TABLE CH04_ST_PERSON CASCADE CONSTRAINTS;

DROP SEQUENCE CH04_ST_PERSON_SEQ;

CREATE TABLE CH04_ST_ADDRESS
(
ID INTEGER NOT NULL,
VERSION INTEGER NOT NULL,
STREET1 VARCHAR2(100),
STREET2 VARCHAR2(100),
CITY VARCHAR2(50),
STATE VARCHAR2(2),
ZIP_CODE INTEGER
)
;

CREATE TABLE CH04_ST_PERSON
(
ID INTEGER NOT NULL,
TYPE VARCHAR(30) NOT NULL,
VERSION INTEGER NOT NULL,
FIRST_NAME VARCHAR2(30),
LAST_NAME VARCHAR2(30),
HOME_ADDRESS INTEGER,
EMAIL VARCHAR2(50),
DEPT VARCHAR2(30),
MANAGER INTEGER,
ANNUAL_SALARY NUMBER(8, 2),
HOURLY_WAGE NUMBER(8, 2)
)
;

ALTER TABLE CH04_ST_ADDRESS
ADD CONSTRAINT INHER_ST_ADDRESS_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE CH04_ST_PERSON
ADD CONSTRAINT INHER_ST_PERSON_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE CH04_ST_PERSON
ADD CONSTRAINT INHER_ST_PERSON_ADDRESS_UK1 UNIQUE
(
HOME_ADDRESS
)
 ENABLE
;

ALTER TABLE CH04_ST_PERSON
ADD CONSTRAINT INHER_ST_PERSON_ADDRESS_FK FOREIGN KEY
(
HOME_ADDRESS
)
REFERENCES CH04_ST_ADDRESS
(
ID
) ENABLE
;

ALTER TABLE CH04_ST_PERSON
ADD CONSTRAINT INHER_ST_PERSON_EMPLOYEE_FK FOREIGN KEY
(
MANAGER
)
REFERENCES CH04_ST_PERSON
(
ID
) ENABLE
;

CREATE SEQUENCE CH04_ST_ADDRESS_SEQ INCREMENT BY 50 START WITH 100 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE CH04_ST_PERSON_SEQ INCREMENT BY 50 START WITH 100 MINVALUE 1 CACHE 20 ;

