ALTER TABLE CH04_TPC_FT_EMPLOYEE DROP CONSTRAINT "INHER_TPC_FT_EMPLOYEE_FK"
;

ALTER TABLE CH04_TPC_FT_EMPLOYEE DROP CONSTRAINT "INHER_TPC_FT_EMPLOYEE_FK1"
;

ALTER TABLE CH04_TPC_PT_EMPLOYEE DROP CONSTRAINT "INHER_TPC_PT_EMPLOYEE_FK"
;

ALTER TABLE CH04_TPC_PT_EMPLOYEE DROP CONSTRAINT "INHER_TPC_PT_EMPLOYEE_FK1"
;

DROP SEQUENCE CH04_TPC_ADDRESS_SEQ;

DROP TABLE CH04_TPC_ADDRESS CASCADE CONSTRAINTS;

DROP TABLE CH04_TPC_FT_EMPLOYEE CASCADE CONSTRAINTS;

DROP SEQUENCE CH04_TPC_PERSON_SEQ;

DROP TABLE CH04_TPC_PT_EMPLOYEE CASCADE CONSTRAINTS;

CREATE TABLE CH04_TPC_ADDRESS
(
ID INTEGER NOT NULL,
VERSION INTEGER NOT NULL,
STREET1 VARCHAR2(100),
STREET2 VARCHAR2(100),
CITY VARCHAR2(50),
STATE VARCHAR2(2),
ZIP_CODE INTEGER
)
;

CREATE TABLE CH04_TPC_FT_EMPLOYEE
(
ID INTEGER NOT NULL,
VERSION INTEGER,
FIRST_NAME VARCHAR2(30),
LAST_NAME VARCHAR2(30),
HOME_ADDRESS INTEGER,
EMAIL VARCHAR2(50),
DEPT VARCHAR2(30),
MANAGER INTEGER,
ANNUAL_SALARY NUMBER(8, 2)
)
;

CREATE TABLE CH04_TPC_PT_EMPLOYEE
(
ID INTEGER NOT NULL,
VERSION INTEGER,
FIRST_NAME VARCHAR2(30),
LAST_NAME VARCHAR2(30),
HOME_ADDRESS INTEGER,
EMAIL VARCHAR2(50),
DEPT VARCHAR2(30),
MANAGER INTEGER,
HOURLY_WAGE NUMBER(8, 2)
)
;

ALTER TABLE CH04_TPC_ADDRESS
ADD CONSTRAINT INHER_TPC_ADDRESS_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE CH04_TPC_FT_EMPLOYEE
ADD CONSTRAINT INHER_TPC_FT_EMPLOYEE_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE CH04_TPC_PT_EMPLOYEE
ADD CONSTRAINT INHER_TPC_PT_EMPLOYEE_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE CH04_TPC_FT_EMPLOYEE
ADD CONSTRAINT INHER_TPC_FT_EMPLOYEE_FK FOREIGN KEY
(
HOME_ADDRESS
)
REFERENCES CH04_TPC_ADDRESS
(
ID
) ENABLE
;

ALTER TABLE CH04_TPC_FT_EMPLOYEE
ADD CONSTRAINT INHER_TPC_FT_EMPLOYEE_FK1 FOREIGN KEY
(
MANAGER
)
REFERENCES CH04_TPC_FT_EMPLOYEE
(
ID
) ENABLE
;

ALTER TABLE CH04_TPC_PT_EMPLOYEE
ADD CONSTRAINT INHER_TPC_PT_EMPLOYEE_FK FOREIGN KEY
(
HOME_ADDRESS
)
REFERENCES CH04_TPC_ADDRESS
(
ID
) ENABLE
;

ALTER TABLE CH04_TPC_PT_EMPLOYEE
ADD CONSTRAINT INHER_TPC_PT_EMPLOYEE_FK1 FOREIGN KEY
(
MANAGER
)
REFERENCES CH04_TPC_FT_EMPLOYEE
(
ID
) ENABLE
;

CREATE SEQUENCE CH04_TPC_ADDRESS_SEQ INCREMENT BY 50 START WITH 100 MINVALUE 1 CACHE 20 ;

CREATE SEQUENCE CH04_TPC_PERSON_SEQ INCREMENT BY 50 START WITH 100 MINVALUE 1 CACHE 20 ;

