ALTER TABLE BUSINESS_CONTACT DROP CONSTRAINT "BUSINESS_CONTACT_ADDRESS_FK"
;

ALTER TABLE BUSINESS_CONTACT DROP CONSTRAINT "BUSINESS_CONTACT_SHIP_ADDR_FK"
;

ALTER TABLE BUSINESS_CONTACT DROP CONSTRAINT "BUSINESS_CONTACT_BILL_ADDR_FK"
;

ALTER TABLE CUSTOMER_ADDRESS DROP CONSTRAINT "CUSTOMER_ADDRESS_ADDRESS_FK"
;

ALTER TABLE CUSTOMER_ADDRESS DROP CONSTRAINT "CUSTOMER_ADDRESS_BUSINESS_FK1"
;

ALTER TABLE CUSTOMER_ORDER DROP CONSTRAINT "CUSTOMER_ORDER_BUSINESS_C_FK1"
;

ALTER TABLE WINE_ITEM DROP CONSTRAINT "WINE_ITEM_WINE_FK"
;

ALTER TABLE WINE_ITEM DROP CONSTRAINT "WINE_ITEM_CUSTOMER_FK"
;

ALTER TABLE WINE_ITEM DROP CONSTRAINT "WINE_ITEM_CUSTOMER_ORDER_FK"
;

ALTER TABLE WINE_SUPPLIER DROP CONSTRAINT "WINE_SUPPLIER_SUPPLIER_FK"
;

ALTER TABLE WINE_SUPPLIER DROP CONSTRAINT "WINE_SUPPLIER_WINE_FK"
;

DROP TABLE ADDRESS;

DROP TABLE BUSINESS_CONTACT;

DROP TABLE CUSTOMER_ADDRESS;

DROP TABLE CUSTOMER_ORDER;

DROP SEQUENCE EJB_SEQ_ID_GEN;

DROP TABLE EJB_TAB_ID_GEN;

DROP TABLE WINE;

DROP TABLE WINE_ITEM;

DROP TABLE WINE_SUPPLIER;

CREATE TABLE ADDRESS
(
ID INTEGER NOT NULL,
VERSION INTEGER,
STREET1 VARCHAR2(4000),
STREET2 VARCHAR2(4000),
CITY VARCHAR2(4000),
STATE CHAR(2),
ZIP_CODE INTEGER
)
;

CREATE TABLE BUSINESS_CONTACT
(
ID INTEGER NOT NULL,
TYPE VARCHAR2(30),
VERSION INTEGER,
FIRST_NAME VARCHAR2(4000),
LAST_NAME VARCHAR2(4000),
PHONE VARCHAR2(15),
PAYMENT_ADDRESS_ID INTEGER,
SHIPPING_ADDRESS_ID INTEGER,
EMAIL VARCHAR2(4000),
BILLING_ADDRESS_ID INTEGER,
MEMBER_STATUS VARCHAR2(30),
DISCOUNT INTEGER,
COMPANY_NAME VARCHAR2(4000),
CC_NUM INTEGER,
CC_EXP_DATE VARCHAR2(7)
)
;

CREATE TABLE CUSTOMER_ADDRESS
(
ADDRESS_ID INTEGER,
CUSTOMER_ID INTEGER
)
;

CREATE TABLE CUSTOMER_ORDER
(
ID INTEGER NOT NULL,
VERSION INTEGER,
CUSTOMER_ID INTEGER NOT NULL,
CREATION_DATE DATE,
STATUS VARCHAR2(30),
STREET1 VARCHAR2(4000),
STREET2 VARCHAR2(4000),
CITY VARCHAR2(4000),
STATE CHAR(2),
ZIP_CODE VARCHAR2(15)
)
;

CREATE TABLE EJB_TAB_ID_GEN
(
ID_NAME VARCHAR2(4000),
SEQ_VALUE NUMBER(*, 0)
)
;

CREATE TABLE WINE
(
ID INTEGER NOT NULL,
VERSION INTEGER,
NAME VARCHAR2(4000) NOT NULL,
DESCRIPTION VARCHAR2(4000),
RETAIL_PRICE NUMBER(38, 2),
RATING NUMBER(4, 2),
COUNTRY VARCHAR2(4000),
REGION VARCHAR2(4000),
VARIETAL VARCHAR2(4000),
YEAR NUMBER(4, 0)
)
;

CREATE TABLE WINE_ITEM
(
ID INTEGER NOT NULL,
TYPE VARCHAR2(30),
VERSION INTEGER,
WINE_ID INTEGER NOT NULL,
QUANTITY INTEGER,
CUSTOMER_ID INTEGER,
CREATED_DATE DATE,
CUSTOMER_ORDER_ID INTEGER,
ORDER_DATE DATE,
SHIP_DATE DATE,
PRICE NUMBER(38, 2),
STATUS VARCHAR2(4000),
STOCK_DATE DATE,
WHOLESALE_PRICE NUMBER(38, 2)
)
;

CREATE TABLE WINE_SUPPLIER
(
WINES_ID INTEGER NOT NULL,
SUPPLIER_ID INTEGER NOT NULL
)
;

ALTER TABLE ADDRESS
ADD CONSTRAINT ADDRESS_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE BUSINESS_CONTACT
ADD CONSTRAINT BUSINESS_CONTACT_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE CUSTOMER_ADDRESS
ADD CONSTRAINT CUSTOMER_ADDRESS_UK1 UNIQUE
(
ADDRESS_ID
)
 ENABLE
;

ALTER TABLE CUSTOMER_ORDER
ADD CONSTRAINT CUSTOMER_ORDER_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE WINE
ADD CONSTRAINT WINE_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE WINE_ITEM
ADD CONSTRAINT PRODUCT_ITEM_PK PRIMARY KEY
(
ID
)
 ENABLE
;

ALTER TABLE WINE_SUPPLIER
ADD CONSTRAINT WINE_SUPPLIER_PK PRIMARY KEY
(
WINES_ID,
SUPPLIER_ID
)
 ENABLE
;

ALTER TABLE BUSINESS_CONTACT
ADD CONSTRAINT BUSINESS_CONTACT_ADDRESS_FK FOREIGN KEY
(
PAYMENT_ADDRESS_ID
)
REFERENCES ADDRESS
(
ID
) ENABLE
;

ALTER TABLE BUSINESS_CONTACT
ADD CONSTRAINT BUSINESS_CONTACT_SHIP_ADDR_FK FOREIGN KEY
(
SHIPPING_ADDRESS_ID
)
REFERENCES ADDRESS
(
ID
) ENABLE
;

ALTER TABLE BUSINESS_CONTACT
ADD CONSTRAINT BUSINESS_CONTACT_BILL_ADDR_FK FOREIGN KEY
(
BILLING_ADDRESS_ID
)
REFERENCES ADDRESS
(
ID
) ENABLE
;

ALTER TABLE CUSTOMER_ADDRESS
ADD CONSTRAINT CUSTOMER_ADDRESS_ADDRESS_FK FOREIGN KEY
(
ADDRESS_ID
)
REFERENCES ADDRESS
(
ID
) ENABLE
;

ALTER TABLE CUSTOMER_ADDRESS
ADD CONSTRAINT CUSTOMER_ADDRESS_BUSINESS_FK1 FOREIGN KEY
(
CUSTOMER_ID
)
REFERENCES BUSINESS_CONTACT
(
ID
) ENABLE
;

ALTER TABLE CUSTOMER_ORDER
ADD CONSTRAINT CUSTOMER_ORDER_BUSINESS_C_FK1 FOREIGN KEY
(
CUSTOMER_ID
)
REFERENCES BUSINESS_CONTACT
(
ID
) ENABLE
;

ALTER TABLE WINE_ITEM
ADD CONSTRAINT WINE_ITEM_WINE_FK FOREIGN KEY
(
WINE_ID
)
REFERENCES WINE
(
ID
) ENABLE
;

ALTER TABLE WINE_ITEM
ADD CONSTRAINT WINE_ITEM_CUSTOMER_FK FOREIGN KEY
(
CUSTOMER_ID
)
REFERENCES BUSINESS_CONTACT
(
ID
) ENABLE
;

ALTER TABLE WINE_ITEM
ADD CONSTRAINT WINE_ITEM_CUSTOMER_ORDER_FK FOREIGN KEY
(
CUSTOMER_ORDER_ID
)
REFERENCES CUSTOMER_ORDER
(
ID
) ENABLE
;

ALTER TABLE WINE_SUPPLIER
ADD CONSTRAINT WINE_SUPPLIER_SUPPLIER_FK FOREIGN KEY
(
SUPPLIER_ID
)
REFERENCES BUSINESS_CONTACT
(
ID
) ENABLE
;

ALTER TABLE WINE_SUPPLIER
ADD CONSTRAINT WINE_SUPPLIER_WINE_FK FOREIGN KEY
(
WINES_ID
)
REFERENCES WINE
(
ID
) ENABLE
;

CREATE SEQUENCE EJB_SEQ_ID_GEN INCREMENT BY 50 START WITH 100 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20 ;

